language: python

python:
  - 2.7
  - 3.5
  - 3.6

os:
  - osx

before_install:
  # install gams
  - curl -O https://d37drm4t2jghv5.cloudfront.net/distributions/25.1.1/macosx/osx_x64_64_sfx.exe;
  - chmod u+x osx_x64_64_sfx.exe
  - ./osx_x64_64_sfx.exe > install.out
  - export PATH=$PATH:$PWD/gams25.1_osx_x64_64_sfx
  # install conda
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p $MINICONDA
  - conda update --yes conda
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  # install ixmp deps
  - conda install --yes -c conda-forge ixmp xlsxwriter xlrd
  - conda remove --force --yes ixmp

install:
  - git clone https://github.com/iiasa/ixmp.git
  - cd ixmp && python setup.py install && cd ..
  - python setup.py install

script:
  - conda install --yes -c conda-forge pytest
  - pytest -v tests
  - messageix-config --model_path=message_ix/model
  - cd doc && pip install -r requirements.txt && make html
